version: '3.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/site
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8018:80
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./docker/php
    volumes:
      - .:/var/www/site
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  node:
    build:
      context: .
      dockerfile: ./docker/node
    volumes:
      - .:/var/www/site:rw
    ports:
      - 3000:3000


